spring:
  main:
    allow-bean-definition-overriding: true
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/service2
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 190407011
  liquibase:
    enabled: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8084

logging:
  level:
    root: warn
    sql: trace
    web: warn

rest:
  template:
    rootUrl: http://localhost:8082



#springdoc:
#  swagger-ui:
#    enabled: true

#springdoc:
#  swagger-ui:
##  disable-swagger-default-url: true
#springdoc.swagger-ui.configUrl=/openapi/swagger-config
#springdoc.swagger-ui.url=/openapi
#springdoc.api-docs.path=/openapi